remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
baseurl: /Portfolio
title: Portfolio

relative_links:
  enabled: true
  collections: true
  
include:
  - README.md
